### ISSUE TITLE
ru_RU.lang

### ISSUE THREAD

**Issue by BiffiMaps** [Pixelmon/PixelmonLauncher-Language#6]
label.minecraft=Minecraft
label.pixelmon=Pixelmon
label.forge=Forge
label.version=Версия
label.installedmods=Моды установлены
label.areyousure=Вы согласны
label.deleteprofile=Вы хотите удалить профиль?
label.profileinstaller=Установщик профиля
label.profileinstallerblurb=Управление своими профилями
label.installing=Установка %s
label.installsuccess=%s успешно установлено!
label.runprofile=Запустить %s
label.installfail=%s не установлено!
label.minecraftoutput=Minecraft Папка
label.minecraftoutput.small=Смотреть
label.selectjava=Выбрать устанвку Java
label.selectjava.small=Мы желаем запустить minecraft
label.settings=Настройки
label.launchersettings=Установить лаунчер
label.volume=Громкость
label.javaargs=Java Аргументы
label.autoupdater=Авто-Обновление
label.profilesettings=Настройки профиля
label.profilesettings.small=Настройте ваш профиль
label.width=Ширина
label.height=Высота
label.additionalargs=Выборочные аргументы
label.profileeditor=Редактор профиля
label.profileeditor.small=Управление своими профилями
label.nopixelmoninstalls=Нет Pixelmon установок
label.noforgeinstalls=Нет Forge установок
label.dragdropothermods=Переместите и отпустите моды сюда!
label.dragdroppixelmon=Чтобы добавить новою версию Pixelmon, Переместите и отпустите  Pixelmon Universal jar сюда!
label.dragdropforge=Чтобы добавить Forge. Переместите и отпустите the Forge installer Jar сюда!
label.visitpixelmonsite=Нажмите здесь, чтобы посетить Pixelmon вебсайт!
label.visitforgesite=Нажмите здесь, чтобы посетить страниц загрузок!
label.basesupportedversion=Base Supported Version
label.profileinstaller.small=Installing a custom profile
label.dragdroppixelmondefined=The required version of Pixelmon is not installed. Drag and drop the Pixelmon Universal jar here!
label.dragdropforgedefined=The required version of Forge is not installed. Drag and drop the Forge Installer jar here!
label.webpage=Webpage:
label.authenticating=Авторизация
label.loggingplayer=Вход %s 
label.hellothere=Hello There
label.logindetails=please authenticate your minecraft account
label.emailusername=Email/Имя пользователя
label.password=Пароль

messagebox.installfailed=Installation Failed
messagebox.minecraftdownloadfailed=Cannot download minecraft.jar!
messagebox.cannotdownload=Cannot download %s
messagebox.incorrectfilesize=Incorrect file size
messagebox.pixelmonfail=Cannot add Pixelmon
messagebox.notforgemod=Not a valid forge mod!
messagebox.unsupportedversion=Unsupported Pixelmon version!
messagebox.invalidpixjar=Not a valid Pixelmon Jar!
messagebox.cantopenfile=Cannot open the file!

checkbox.deletelocalfiles=Delete local files
checkbox.customwindowsize=Use custom window size
checkbox.openoutputdialog=Keep output dialog open after Minecraft exits
checkbox.forcereinstall=Reinstall all libraries next install

button.logout=Logout
button.browse=Browse
button.continue=Continue
button.close=Close
button.cancel=Cancel
button.selectjava=Select Java Install
button.checknow=Check now
button.configure=Configure
button.settings=Settings
button.cancelchanges=Cancel Changes
button.save=Save
button.deleteprofile=Delete Profile
button.installprofile=Install Profile

tooltip.newprofile=Create new profile
tooltip.openfolder=Browse to profile folder
tooltip.configureprofile=Configure profile
tooltip.play=Play
tooltip.install=Install
tooltip.mute=Music
tooltip.openoutputdialog=This keep the output text from Minecraft open even after Minecraft have exited
tooltip.forcereinstall=This forces the launcher to re-download all the library dependencies the next time you play this profile

menu.website=Pixelmon Website
menu.donate=Donate
menu.servers=Servers
menu.settings=Settings

install.createdirs=Creating Directories
install.copypixelmon=Copying Pixelmon Jar
install.libraries=Installing Libraries
install.assets=Installing Assets
install.mods=Installing Mods
install.extractjar=Extracting Jar: %s
install.download=Downloading %s
install.validate=Validating %s

**Comment by BiffiMaps** [comment]
label.minecraft=Minecraft
label.pixelmon=Pixelmon
label.forge=Forge
label.version=Версия
label.installedmods=Моды установлены
label.areyousure=Вы согласны
label.deleteprofile=Вы хотите удалить профиль?
label.profileinstaller=Установщик профиля
label.profileinstallerblurb=Управление своими профилями
label.installing=Установка %s
label.installsuccess=%s успешно установлено!
label.runprofile=Запустить %s
label.installfail=%s не установлено!
label.minecraftoutput=Minecraft Папка
label.minecraftoutput.small=Смотреть
label.selectjava=Выбрать устанвку Java
label.selectjava.small=Мы желаем запустить minecraft
label.settings=Настройки
label.launchersettings=Установить лаунчер
label.volume=Громкость
label.javaargs=Java Аргументы
label.autoupdater=Авто-Обновление
label.profilesettings=Настройки профиля
label.profilesettings.small=Настройте ваш профиль
label.width=Ширина
label.height=Высота
label.additionalargs=Выборочные аргументы
label.profileeditor=Редактор профиля
label.profileeditor.small=Управление своими профилями
label.nopixelmoninstalls=Нет Pixelmon установок
label.noforgeinstalls=Нет Forge установок
label.dragdropothermods=Переместите и отпустите моды сюда!
label.dragdroppixelmon=Чтобы добавить новою версию Pixelmon, Переместите и отпустите  Pixelmon Universal jar сюда!
label.dragdropforge=Чтобы добавить Forge. Переместите и отпустите the Forge installer Jar сюда!
label.visitpixelmonsite=Нажмите здесь, чтобы посетить Pixelmon вебсайт!
label.visitforgesite=Нажмите здесь, чтобы посетить страниц загрузок!
label.basesupportedversion=Base Supported Version
label.profileinstaller.small=Installing a custom profile
label.dragdroppixelmondefined=The required version of Pixelmon is not installed. Drag and drop the Pixelmon Universal jar here!
label.dragdropforgedefined=The required version of Forge is not installed. Drag and drop the Forge Installer jar here!
label.webpage=Webpage:
label.authenticating=Авторизация
label.loggingplayer=Вход %s 
label.hellothere=Hello There
label.logindetails=please authenticate your minecraft account
label.emailusername=Email/Имя пользователя
label.password=Пароль

messagebox.installfailed=Installation Failed
messagebox.minecraftdownloadfailed=Cannot download minecraft.jar!
messagebox.cannotdownload=Cannot download %s
messagebox.incorrectfilesize=Incorrect file size
messagebox.pixelmonfail=Cannot add Pixelmon
messagebox.notforgemod=Not a valid forge mod!
messagebox.unsupportedversion=Unsupported Pixelmon version!
messagebox.invalidpixjar=Not a valid Pixelmon Jar!
messagebox.cantopenfile=Cannot open the file!

checkbox.deletelocalfiles=Delete local files
checkbox.customwindowsize=Use custom window size
checkbox.openoutputdialog=Keep output dialog open after Minecraft exits
checkbox.forcereinstall=Reinstall all libraries next install

button.logout=Logout
button.browse=Browse
button.continue=Continue
button.close=Close
button.cancel=Cancel
button.selectjava=Select Java Install
button.checknow=Check now
button.configure=Configure
button.settings=Settings
button.cancelchanges=Cancel Changes
button.save=Save
button.deleteprofile=Delete Profile
button.installprofile=Install Profile

tooltip.newprofile=Create new profile
tooltip.openfolder=Browse to profile folder
tooltip.configureprofile=Configure profile
tooltip.play=Play
tooltip.install=Install
tooltip.mute=Music
tooltip.openoutputdialog=This keep the output text from Minecraft open even after Minecraft have exited
tooltip.forcereinstall=This forces the launcher to re-download all the library dependencies the next time you play this profile

menu.website=Pixelmon Website
menu.donate=Donate
menu.servers=Servers
menu.settings=Settings

install.createdirs=Creating Directories
install.copypixelmon=Copying Pixelmon Jar
install.libraries=Installing Libraries
install.assets=Installing Assets
install.mods=Installing Mods
install.extractjar=Extracting Jar: %s
install.download=Downloading %s
install.validate=Validating %s

**Comment by isiliden** [comment]
Please read Githubs documentation for making this a pull request.
